SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+08:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE TABLE IF NOT EXISTS `accounts` (
	`username` VARCHAR(24) NOT NULL,
	`password` VARCHAR(32) NOT NULL,
	`email` VARCHAR(32) NOT NULL,
	PRIMARY KEY (`username`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `tokenlist` (
	`token` VARCHAR(64) NOT NULL,
	`username` VARCHAR(24) NOT NULL,
	`timestamp` INT(10) unsigned NOT NULL,
	PRIMARY KEY (`token`),
	FOREIGN KEY (`username`) REFERENCES accounts (`username`) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO `accounts` SET `username`="testuser", `password`="179ad45c6ce2cb97cf1029e212046e81", `email`="test@example.com";

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
